"""Constants for the GARLYN Scale integration."""

DOMAIN = "garlyn_scale"

CONF_SCALE_ID = "scale_id"
CONF_SCALE_NAME = "scale_name"
CONF_WEBHOOK_ID = "webhook_id"
CONF_PROFILES = "profiles"
CONF_SPARKY_URL = "sparky_url"

CONF_PROFILE_NAME = "name"
CONF_PROFILE_ID = "profile_id"
CONF_PROFILE_PIN = "profile_pin"
CONF_SEX = "sex"
CONF_DATE_OF_BIRTH = "date_of_birth"
CONF_HEIGHT_CM = "height_cm"
CONF_ATHLETE_MODE = "athlete_mode"
CONF_REFERENCE_STANDARD = "reference_standard"
CONF_SPARKY_ENABLED = "sparky_enabled"
CONF_SPARKY_API_KEY = "sparky_api_key"

DEFAULT_SCALE_NAME = "GARLYN Bodyscan Master"
TRANSPORT_PROTOCOL_VERSION = 1
ALGORITHM_VERSION = "bodyFatScaleAlg_2.2.2"

SPARKY_HEALTH_DATA_PATH = "/api/health-data"
SPARKY_SOURCE = "GARLYN Scale via Home Assistant"
SPARKY_REQUEST_TIMEOUT_SECONDS = 15
SPARKY_RETRY_INITIAL_SECONDS = 60
SPARKY_RETRY_MAX_SECONDS = 3_600
MAX_SPARKY_OUTBOX_ITEMS = 512
MAX_SPARKY_DAY_WATERMARKS = 10_000

MAX_WEBHOOK_PAYLOAD_BYTES = 16_384
DEFAULT_DEDUPLICATION_CACHE_SIZE = 256
